- hosts: local
  connection: local
  tasks:
    - name: create workdir
      file:
        path: '{{ playbook_dest }}'
        state: directory
      tags: [ 'prepare' ]

    - name: create pull script
      template:
        dest: '{{ playbook_dest }}/pull.sh'
        src: '{{ source_dir }}/pull.sh'
        mode: 0755
      tags: [ 'prepare_external' ]

    - name: create run script
      template:
        dest: '{{ playbook_dest }}/run.sh'
        src: '{{ source_dir }}/run.sh'
        mode: 0755
      tags: [ 'prepare' ]

    - name: pull image
      command: '{{ playbook_dest }}/pull.sh'
      tags: [ 'pull' ]

    - name: docker run
      command: '{{ playbook_dest }}/run.sh'
      tags: ['run']

    - name: docker stop
      command: 'docker stop {{ container_name }}'
      tags: [ 'destroy' ]

    - name: erase workdir
      command: 'rm -r {{ playbook_dest }}/'
      tags: [ 'clean' ]

