chat:
    model:
        model: langchain.chat_models.ChatOpenAI
        kwargs:
            temperature: 0.7
            streaming: True
            model_name: gpt-3.5-turbo

    embeddings:
        embeddings: langchain_community.embeddings.OpenAIEmbeddings
        kwargs:
            model: text-embedding-ada-002
            chunk_size: 1000

    memory:
        memory: langchain.memory.ConversationSummaryBufferMemory
        kwargs:
            return_messages: True
            memory_key: chat_history
            output_key: answer

    history:
        history: langchain.memory.ChatMessageHistory
        kwargs:
            return_messages: True

